services:
  backend:
    build: ./backend
    container_name: pombo-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=file:./dev.db
      - PORT=3001
    volumes:
      - backend_data:/app/prisma
    networks:
      - pombo-network
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      target: production
    container_name: pombo-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - pombo-network
    restart: unless-stopped

volumes:
  backend_data:
    driver: local

networks:
  pombo-network:
    driver: bridge
